# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  test:

services:

  ca.hdfc.example.com:
    container_name: ca.hdfc.example.com
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hdfc
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b hdfccaadmin:hdfccaadminpw -d'
    volumes:
      - ../organizations/fabric-ca/hdfc:/etc/hyperledger/fabric-ca-server
    networks:
      - test

  ca.sbi.example.com:
    container_name: ca.sbi.example.com
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-sbi
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b sbicaadmin:sbicaadminpw -d'
    volumes:
      - ../organizations/fabric-ca/sbi:/etc/hyperledger/fabric-ca-server
    networks:
      - test

  ca.npci.example.com:
    container_name: ca.npci.example.com
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-npci
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b npcicaadmin:npcicaadminpw -d'
    volumes:
      - ../organizations/fabric-ca/npci:/etc/hyperledger/fabric-ca-server
    networks:
      - test
